name: ser20 mac ci
on: [push, pull_request]

jobs:
  test_ser20_macos:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - CMAKE_OPTIONS: '-DWITH_WERROR=ON'
            COMPILER: 'clang++'
            XCODE_VERSION: 16.2.0
            NAME: macos-latest-clang-xcode16.2
          - CMAKE_OPTIONS: '-DWITH_WERROR=ON'
            COMPILER: 'clang++'
            XCODE_VERSION: 16.1.0
            NAME: macos-latest-clang-xcode16.1
          - CMAKE_OPTIONS: '-DWITH_WERROR=ON'
            COMPILER: 'clang++'
            XCODE_VERSION: 15.4.0
            NAME: macos-latest-clang-xcode15.4
          - CMAKE_OPTIONS: '-DWITH_WERROR=ON'
            COMPILER: 'clang++'
            XCODE_VERSION: 15.3.0
            NAME: macos-latest-clang-xcode15.3
          - CMAKE_OPTIONS: '-DWITH_WERROR=ON'
            COMPILER: 'clang++'
            XCODE_VERSION: 15.2.0
            NAME: macos-latest-clang-xcode15.2
          - CMAKE_OPTIONS: '-DWITH_WERROR=ON'
            COMPILER: 'clang++'
            XCODE_VERSION: 15.1.0
            NAME: macos-latest-clang-xcode15.1
          - CMAKE_OPTIONS: '-DWITH_WERROR=ON'
            COMPILER: 'clang++'
            XCODE_VERSION: 15.0.1
            NAME: macos-latest-clang-xcode15.0.1
    name: ${{ matrix.name }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ matrix.XCODE_VERSION }}

    - name: build and test
      shell: bash
      env:
        CMAKE_OPTIONS: ${{ matrix.CMAKE_OPTIONS }}
        COMPILER: ${{ matrix.COMPILER }}
      run: |
        set -ex
        # Set compiler and env variables
        export CXX=${COMPILER}
        ${CXX} --version

        # Build ser20 and test
        cmake --version
        rm -rf build && mkdir build && cd build
        cmake ${CMAKE_OPTIONS} .. && make -j4 VERBOSE=1
        ctest . --output-on-failure
