name: ser20 mac ci
on: [push, pull_request]

jobs:
  test_ser20_macos:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { XCODE_VERSION: 16.2.0 }
          - { XCODE_VERSION: 15.4.0 }
    name: macos-latest-clang-${{ matrix.XCODE_VERSION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.XCODE_VERSION }}

      - name: build and test
        shell: bash
        run: |
          set -ex
          # Set compiler and env variables
          export CXX=clang++
          export CC=clang
          ${CXX} --version

          # Build ser20 and test
          cmake --version
          rm -rf build && mkdir build && cd build
          cmake -DWITH_WERROR=ON .. && make -j4 VERBOSE=1
          ctest . --output-on-failure
